version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:20.12.0-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:e0:62:ab:fd:a2:40:bc:4f:a8:e0:92:b6:bb:ff:1c"
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building for production environment
          command: npm run build --prod --build-optimizer --no-progress

      - run:
          name: Install Chrome Headless
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - run:
          name: Karma Tests
          command: npm run test --single-run --no-progress
          environment:
            CHROME_BIN: /usr/bin/google-chrome
      - run:
          name: Configure git
          command: |
            git config user.email "rusugabriel13@gmail.com"
            git config user.name "Circle CI"
      - run:
          name: Deploy to gh-pages
          command: npm run deploy
